### ISSUE TITLE
Processed data is missing

### ISSUE THREAD

**Issue by pablo-gar** [berenslab/mini-atlas#1]
The following folders are empty in the [processed dir](https://github.com/berenslab/mini-atlas/tree/master/data/processed)

- ephys
- reduced-allen-data
- rnaseq

**Comment by Visdoom** [comment]
Hey @pablo-gar ,
Which data are you looking for exactly? You might find it in the .csv files in data. There are the extracted features for morph, ephys and RNA.
If you want to reproduce the entire analyses you will have to download the raw data from the repositories mentioned.

**Comment by pablo-gar** [comment]
Thanks for the pointer, I was hoping to get the t-SNE embeddings for the patch-seq cells as shown in fig 1c-e (black symbols), and 3 a-c.

I was wondering if you saved those, it would save time instead of downloading and re-running the python notebooks

**Comment by dkobak** [comment]
Oh I see. I could export these embeddings and add them to this repository. Would you also need the t-SNE embedding coordinates for the Allen institute data in Figure 1c-e (colored points)? Or only black symbols in Figure 1c-e?

**Comment by pablo-gar** [comment]
Having the coordinates for the Allen institute data would help too

**Comment by pablo-gar** [comment]
@dkobak have you had a chance to get the embeddings?

**Comment by dkobak** [comment]
@pablo-gar Sorry for delay... I was swamped with other stuff. Is this still of interest to you?

**Comment by pablo-gar** [comment]
It is still of interest. For context, this is to host the data in [cellxgene](https://cellxgene.cziscience.com/) as part of a collaboration between the cellxgene team and BICCN.

Thanks @dkobak

**Comment by dkobak** [comment]
Hi Pablo,

sorry that it took me ages. So now you can find t-SNE coordinates in `data/processed/export`. The file for Figure 1 is `coverage-tsnes.csv` and it looks like this:

```
,t-SNE position x,t-SNE position y,Which t-SNE
20171204_sample_2,-43.57,35.26,Excitatory
20171204_sample_4,-9.3,27.95,Excitatory
20171204_sample_5,0.41,22.18,Excitatory
...
20180103_sample_4,,,           
20180103_sample_5,0.85,20.97,Excitatory
...
20180213_sample_5,-49.03,-34.93,Pvalb/Sst
20180215_sample_1,-51.46,8.97,Pvalb/Sst
...
```

So I put all three t-SNEs shown in Figure 1 into one table, the last column shows which panel it's coming from. If you want the reference data from Yao et al., then it's `data/processed/rnaseq/10x-tsne-exc.pickle`, `10x-tsne-pvsst.pickle`, `10x-tsne-viplamp.pickle`.

The file for Figure 3 is `morpho-electric-tsnes.csv` and it looks like this:

```
,Ephys t-SNE x,Ephys t-SNE y,Morph t-SNE x,Moprh t-SNE y,Morphoelectric t-SNE x,Morphoelectric t-SNE y
20171204_sample_2,32.98,-30.54,39.88,15.38,24.94,13.32
20171204_sample_4,32.72,-31.22,34.11,10.69,24.09,12.44
20171204_sample_5,33.52,-31.38,37.36,10.76,24.25,12.99
20171204_sample_6,34.38,-32.61,38.88,7.87,23.21,13.35
20171207_sample_1,57.06,-3.56,34.21,15.16,38.07,10.32
20171207_sample_2,56.69,-3.55,40.06,11.18,38.19,9.6
20171207_sample_6,-9.07,-3.05,38.88,14.49,22.72,10.37
20171207_sample_7,-8.98,-3.07,35.95,8.56,22.67,10.17
20171219_sample_1,45.16,-0.51,31.43,11.53,34.82,3.8
20171219_sample_2,45.08,0.11,39.31,11.17,32.51,8.38
20171219_sample_3,42.04,-0.7,32.72,10.83,34.26,4.51
20171219_sample_4,41.18,4.63,,,,
20171219_sample_6,39.46,8.2,37.93,6.74,31.07,10.81
```

so here again all three tSNEs are in one table, in different columns. Not all cells have morphologies, therefore some values are missing in the morphological columns.

Let me know if anything is unclear!
